config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: {
    registrations: 'students/registrations'
  }
  devise_for :teachers
  devise_for :admins

  root to: "home#index"
  resources :details, only: [:edit, :update]
  resources :academics
  resources :students
  resources :teachers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :detail
  has_one :academic
end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  def create
    super
    @detail = Detail.new(detail_params)
    @detail.student_id= resource.id
    @detail.save
    @academic= Academic.new(academic_params)
    @academic.student_id = resource.id
    @academic.save
  end

  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end
private
def detail_params
  params.require(:student).permit(:Name,:Dob, :Blood_group, :Fathers_name,:Parent_address,:Phone_number, :Achievement, :student_id)
end
def academic_params
  params.require(:student).permit(:Attendance,:Midterm_marks,:Midterm_percentage, :Annual_marks, :Annual_Percentage, :Fee_details, :Remark, :student_id)
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController <ApplicationController
  before_action :signed_in_user

  def index
    @students=Student.all
  end

  def show
      @student = Student.find(params[:id])
  end

end

app/views/students/index.html.erb
<h1 style="text-align: center">Student listing page</h1>
<table>
  <thead>
  <tr>
    <th colspan="1">Name</th>
    <th>Email</th>
    <th colspan="3">Action</th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do|student| %>
    <tr>
      <td><%= student.detail.Name %></td>
      <td><%= student.email %></td>
      <td><%= link_to 'show', student_path(student) %></td>
      <% if admin_signed_in? %>
      <td> <%=button_to 'delete', student, method: :delete, data: {confirm: "Are you sure?" }%> </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/students/show.html.erb
<h1>Student details page</h1>
<table>
  <tbody>
  <tr>
    <h3><b>Details</b></h3>
    <th>Name:</th>
    <td><%= @student.detail.Name %></td>
  </tr>
  <tr>
    <th>Dob:</th>
    <td><%= @student.detail.Dob %></td>
  </tr>
  <tr>
    <th>Blood_group:</th>
    <td><%= @student.detail.Blood_group %></td>
  </tr>
  <tr>
    <th>Fathers_name:</th>
    <td><%= @student.detail.Fathers_name %></td>
  </tr>
  <tr>
    <th>Parent_address:</th>
    <td><%= @student.detail.Parent_address %></td>
  </tr>
  <tr>
    <th>Phone_number:</th>
    <td><%= @student.detail.Phone_number%></td>
  </tr>
  <tr>
    <th>Achievement:</th>
    <td><%= @student.detail.Achievement%></td>
  </tr>
  </tbody>
</table>

<% if admin_signed_in? or student_signed_in? %>
<td> <%= link_to 'Edit', edit_detail_path(@student.detail.id) %> </td>
<% end %>

<p>
  <br/>
</p>

<table>
  <tbody>
  <tr>
    <h3><b>Academics</b></h3>
    <th>Attendance:</th>
    <td><%= @student.academic.Attendance %></td>
  </tr>
  <tr>
    <th>Midterm_marks:</th>
    <td><%= @student.academic.Midterm_marks %></td>
  </tr>
  <tr>
    <th>Midterm_percentage:</th>
    <td><%= @student.academic.Midterm_percentage %></td>
  </tr>
  <tr>
    <th>Annual_marks:</th>
    <td><%= @student.academic.Annual_marks %></td>
  </tr>
  <tr>
    <th>Annual_percentage:</th>
    <td><%= @student.academic.Annual_percentage %></td>
  </tr>
  <tr>
    <th>Fee_details:</th>
    <td><%= @student.academic.Fee_details%></td>
  </tr>
  <tr>
    <th>Remark:</th>
    <td><%= @student.academic.Remark%></td>
  </tr>
  </tbody>
</table>
<% if teacher_signed_in? or admin_signed_in? %>
<td> <%= link_to 'Edit', edit_academic_path(@student.academic.id)%> </td>
<% end %>