config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: {
    registrations: 'students/registrations'
  }
  devise_for :teachers
  devise_for :admins

  root to: "home#index"
  resources :details, only: [:edit, :update]
  resources :academics
  resources :students
  resources :teachers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1 style="text-align: center">School Management System</h1>
<% unless admin_signed_in? or teacher_signed_in? or student_signed_in? %>
  <%= button_to "Admin", new_admin_session_path %></br>
  <%= button_to "Teacher",new_teacher_session_path %></br>
  <%= button_to "Student",new_student_session_path %>
<%end %>

<div style="text-align: center">
<% if admin_signed_in? %>
  <%= link_to 'student_list',students_path %> |
  <%= link_to 'Teacher list',teachers_path %> <br/>
  <p>
  <%=link_to 'Create new student record', new_student_registration_path %></br>
  <%=link_to'Create new Teacher record', new_teacher_registration_path %>
  </p>
  <%= button_to "logout", destroy_admin_session_path, method: :delete %>
<%end %>
</div>

<% if student_signed_in? %>
  <%= link_to 'Myrecord', student_path(current_student.id)%>
  <%= button_to "logout", destroy_student_session_path, method: :delete %>
<%end %>

<% if teacher_signed_in? %>
  <%= link_to 'student list',students_path %>
  <%= button_to "logout", destroy_teacher_session_path, method: :delete %>
<%end %>